#!/usr/bin/env bash
# report_module.sh: Summarise HLS, Fusion and Power reports for a single hardware module.
# Usage:  ./report_module.sh <MODULE_PATH>
# Example: ./report_module.sh GSCore/BSU
# <MODULE_PATH> should match the PROJ_PATH used when invoking `make hls`,
# i.e. the relative path (from repository root) to the module directory.

set -euo pipefail

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 <MODULE_PATH> (e.g. GSCore/QSU)" >&2
  exit 1
fi

MODULE_PATH="$1"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

MODULE_NAME="$(basename "${MODULE_PATH}")"
HLS_OUT_DIR="${MODULE_NAME}_build_hls"

# Directories generated by the build flow -------------------------------------------------------------
HLS_DIR="$SCRIPT_DIR/../A2_hls/${MODULE_PATH}/build_hls"
FUSION_DIR="$SCRIPT_DIR/../A4_fusion/${MODULE_PATH}/build_fc"
POWER_DIR="$SCRIPT_DIR/../A5_pwr/${MODULE_PATH}/build_fc"

# Sanity-check that the expected reports exist --------------------------------------------------------
RTL_RPT="$HLS_DIR/${HLS_OUT_DIR}/${MODULE_NAME}.v1/rtl.rpt"
POWER_RPT_HLS="$HLS_DIR/${HLS_OUT_DIR}/${MODULE_NAME}.v1/power.rpt"
CYCLE_RPT="$HLS_DIR/${HLS_OUT_DIR}/${MODULE_NAME}.v1/cycle.rpt"
LOG_VCS="$HLS_DIR/${HLS_OUT_DIR}.log"
QOR_RPT="$FUSION_DIR/qor.rpt"
POWER_RPT_SYN="$POWER_DIR/power.allavg.rpt"

report_file() {
  local HEADER="$1"; shift
  local FILE="$1"; shift
  local GREP_ARGS=("$@")
  echo "======================================================================================================="
  if [[ -f "$FILE" ]]; then
    grep "${GREP_ARGS[@]}" "$FILE"
  else
    echo "[Missing] $FILE" >&2
  fi
}

# Emit summaries --------------------------------------------------------------------------------------
report_file "RTL TOTAL"        "$RTL_RPT"        TOTAL
report_file "HLS Power"        "$POWER_RPT_HLS" pre_pwropt_default_Verilog -A 4
report_file "Latency"          "$CYCLE_RPT"     Processes/Blocks -A 7

# VCS log is large; print last 100 lines around metric ------------------------------------------------
echo "======================================================================================================="
if [[ -f "$LOG_VCS" ]]; then
  grep "V C S" -A 100 "$LOG_VCS"
else
  echo "[Missing] $LOG_VCS" >&2
fi

report_file "Fusion Area"      "$QOR_RPT"       "Cell Area"
report_file "Post-Syn Power"   "$POWER_RPT_SYN" Total -A 5
echo "=======================================================================================================" 
